services:
  backend:
    build: ./backend
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - ./backend:/home/node/app
      - /home/node/app/node_modules
      - /home/node/app/generated
    env_file:
      - ./backend/.env
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      - API_PORT=${API_PORT}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?schema=public
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/home/node/app
    restart: unless-stopped
    depends_on:
      - backend
    env_file:
      - ./frontend/.env
  postgres:
    image: postgres:14.17
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    env_file:
      - ./.env
