services:
  backend:
    build: ./backend
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - ./backend:/home/node/app
    env_file:
      - ./backend/.env
    environment:
      - API_PORT=${API_PORT}
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/home/node/app
    env_file:
      - ./frontend/.env
  postgres:
    image: postgres:14.17
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    env_file:
      - ./.env
