FROM node:20.19-slim

WORKDIR /home/node/app

RUN apt-get update && apt-get install -y openssl

RUN npm i -g pnpm

COPY package.json pnpm-lock.yaml ./

RUN pnpm install

COPY . .

RUN pnpm prisma generate

USER node

ENTRYPOINT [ "pnpm", "run", "start:dev" ]